-- ==========================================
-- SUPABASE SCHEMA FOR WHATSAPP AUTO-REPLY BOT
-- Run this in your Supabase Project -> SQL Editor
-- ==========================================

-- 1. Create Bot Settings Table
CREATE TABLE IF NOT EXISTS bot_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Seed default settings
INSERT INTO bot_settings (key, value) VALUES
  ('bot_active', 'true'),
  ('reply_delay', '10000'), -- 10 seconds responsive delay
  ('ai_personality', 'You are Ollie, a friendly and highly intelligent AI WhatsApp assistant created for Oliver. Keep replies casual, incredibly natural, and human-like. Never mention you are an AI.'),
  ('auto_reply_groups', 'false'),
  ('owner_name', 'Oliver'),
  ('bot_name', 'Ollie'),
  ('owner_phone', '254705760434'),
  ('poster_url', 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80'),
  ('poster_trigger', 'poster'),
  ('bot_rules', '1. Act as Ollie, Oliver\'s personal assistant.\n2. If the sender asks for a "poster", "flyer", or "brochure", make sure to mention you are sending the official poster.\n3. Always match their vibe (casual/friendly/formal).\n4. Keep answers short and sweet (1-2 sentences).')
ON CONFLICT (key) DO NOTHING;

-- 2. Create Blocked Contacts Table
CREATE TABLE IF NOT EXISTS blocked_contacts (
  jid TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  is_group BOOLEAN DEFAULT false NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Contact Profiles Table
CREATE TABLE IF NOT EXISTS contact_profiles (
  jid TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  vibe TEXT DEFAULT 'friendly' NOT NULL,
  message_count INTEGER DEFAULT 1 NOT NULL,
  last_seen TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  notes TEXT DEFAULT ''
);

-- 4. Create Messages Table
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  jid TEXT NOT NULL,
  sender_name TEXT NOT NULL,
  message_text TEXT NOT NULL,
  reply_text TEXT,
  reply_status TEXT DEFAULT 'pending' NOT NULL,
  is_group BOOLEAN DEFAULT false NOT NULL,
  is_meeting BOOLEAN DEFAULT false NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Create Meeting Alerts Table
CREATE TABLE IF NOT EXISTS meeting_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender TEXT NOT NULL,
  message TEXT NOT NULL,
  detected_time TEXT DEFAULT '' NOT NULL,
  detected_date TEXT DEFAULT '' NOT NULL,
  alert_type TEXT DEFAULT 'meeting' NOT NULL,
  is_read BOOLEAN DEFAULT false NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Create Auth Session Table (For cloud persistence)
CREATE TABLE IF NOT EXISTS auth_session (
  file_id TEXT PRIMARY KEY,
  data TEXT NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Disable Row Level Security (RLS) for easy connection
ALTER TABLE bot_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE blocked_contacts DISABLE ROW LEVEL SECURITY;
ALTER TABLE contact_profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE meeting_alerts DISABLE ROW LEVEL SECURITY;
ALTER TABLE auth_session DISABLE ROW LEVEL SECURITY;
